# -*- coding: utf-8 -*-
"""
/***************************************************************************
 cmg
                                 A QGIS plugin
 descripcion corta
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-27
        copyright            : (C) 2020 by Servisoft
        email                : contacto@servisoft.com.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load cmg class from file cmg.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cmg_toolbox import cmg
    return cmg(iface)
